"""socle initial

Revision ID: 241581395051
Revises: 
Create Date: 2026-09-01 14:15:27.889016
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '241581395051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('is_demo_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('holiday_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('quota_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('module', sa.Enum('GARDES', 'PERMANENCES_JOUR', name='module', native_enum=False, length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('painful_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rest_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('enforcement', sa.Enum('FERME', 'SOUPLE', name='enforcement', native_enum=False, length=40), nullable=False),
    sa.Column('min_hours_between', sa.Float(), nullable=True),
    sa.Column('max_count_window_days', sa.Integer(), nullable=True),
    sa.Column('max_count_value', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_weekends', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('is_demo_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rule_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_rule_profile')
    )
    op.create_table('urgency_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('tiers_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_urgency_profile')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_medecin', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=80), nullable=False),
    sa.Column('hash', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garde_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('module', sa.Enum('GARDES', 'PERMANENCES_JOUR', name='module', native_enum=False, length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('default_coverage_mode', sa.Enum('A', 'B', name='coveragemode', native_enum=False, length=40), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('duration_class', sa.String(length=40), nullable=False),
    sa.Column('count_weight', sa.Float(), nullable=False),
    sa.Column('exchange_class_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('horaires_a_valider', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['quota_categories.id'], ),
    sa.ForeignKeyConstraint(['exchange_class_id'], ['exchange_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('holiday_pair_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('include_eve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['holiday_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('SENIOR', 'ASSISTANT', name='status', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('quarters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_id', 'index', name='uq_quarter_index')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=60), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_demo_hypothesis', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('GARDES', 'PERMANENCES_JOUR', name='module', native_enum=False, length=40), nullable=False),
    sa.Column('state', sa.Enum('PREPARATION', 'OUVERTE', 'CLOTUREE', 'RESOLUTION_NON_REPONDANTS', 'PRETE', 'ARCHIVEE', name='campaignstate', native_enum=False, length=40), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(), nullable=False),
    sa.Column('grace_period_hours', sa.Integer(), nullable=False),
    sa.Column('reminder_offsets_days', sa.String(length=80), nullable=False),
    sa.Column('holiday_pair_requirement', sa.Enum('VERT', 'VERT_ORANGE', name='holidayrequirement', native_enum=False, length=40), nullable=False),
    sa.Column('default_conversion_done_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id', 'module', name='uq_campaign_quarter')
    )
    op.create_table('eligibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('L1', 'L2', name='line', native_enum=False, length=40), nullable=False),
    sa.Column('garde_type_id', sa.Integer(), nullable=True),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garde_type_id'], ['garde_types.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'line', 'garde_type_id', name='uq_eligibility_scope')
    )
    op.create_table('engine_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=60), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('rule_profile_label', sa.String(length=120), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=80), nullable=False),
    sa.Column('input_snapshot_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('EN_COURS', 'TERMINEE', 'ECHEC', name='enginerunstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('line', sa.Enum('L1', 'L2', name='line', native_enum=False, length=40), nullable=True),
    sa.Column('total', sa.Boolean(), nullable=False),
    sa.Column('reduction_ratio', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['quota_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garde_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garde_type_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('coverage_mode', sa.Enum('A', 'B', name='coveragemode', native_enum=False, length=40), nullable=True),
    sa.Column('is_weekend_block', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garde_type_id'], ['garde_types.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garde_type_id', 'local_date', name='uq_occurrence_type_date')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('recipient_profile_id', sa.Integer(), nullable=True),
    sa.Column('recipient_label', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('anonymised', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('quota_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('L1', 'L2', name='line', native_enum=False, length=40), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('carried_to_next_campaign', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['quota_categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quota_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('L1', 'L2', name='line', native_enum=False, length=40), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('minimum', sa.Float(), nullable=True),
    sa.Column('maximum', sa.Float(), nullable=True),
    sa.Column('hard_minimum', sa.Boolean(), nullable=False),
    sa.Column('hard_maximum', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['quota_categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'year_id', 'category_id', 'line', name='uq_quota_scope')
    )
    op.create_table('quotite_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenths', sa.Integer(), nullable=False),
    sa.Column('tima_label', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('structural_json', sa.Text(), nullable=False),
    sa.Column('sensitivity_json', sa.Text(), nullable=False),
    sa.Column('feasibility_json', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('L1', 'L2', name='line', native_enum=False, length=40), nullable=False),
    sa.Column('required_status', sa.Enum('SENIOR', 'ASSISTANT', name='status', native_enum=False, length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['garde_occurrences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurrence_id', 'line', name='uq_post_occurrence_line')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engine_run_id', sa.Integer(), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_breakdown_json', sa.Text(), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('unfilled_json', sa.Text(), nullable=False),
    sa.Column('tensions_json', sa.Text(), nullable=False),
    sa.Column('quota_gaps_json', sa.Text(), nullable=False),
    sa.Column('orange_count', sa.Integer(), nullable=False),
    sa.Column('default_availability_count', sa.Integer(), nullable=False),
    sa.Column('diversity_min', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engine_run_id'], ['engine_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_run_id', 'variant_index', name='uq_proposal')
    )
    op.create_table('quota_target_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quota_target_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('old_target', sa.Float(), nullable=True),
    sa.Column('new_target', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quota_target_id'], ['quota_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NON_COMMENCEE', 'BROUILLON', 'VALIDEE', 'VERROUILLEE', name='submissionstate', native_enum=False, length=40), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('last_reminder_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'profile_id', name='uq_submission_person')
    )
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('L1', 'L2', name='line', native_enum=False, length=40), nullable=True),
    sa.Column('color', sa.Enum('VERT', 'ORANGE', 'ROUGE', 'DISPO_DEFAUT', name='color', native_enum=False, length=40), nullable=False),
    sa.Column('is_declared', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('UTILISATEUR', 'CONVERSION_NON_REPONSE', 'ADMIN', name='availabilitysource', native_enum=False, length=40), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['garde_occurrences.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'occurrence_id', 'line', name='uq_availability_scope')
    )
    op.create_table('proposal_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['coverage_posts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'post_id', name='uq_proposal_post')
    )
    op.create_table('schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('GENERE', 'EN_REVISION', 'VALIDE', 'PUBLIE', 'REMPLACE', name='schedulestate', native_enum=False, length=40), nullable=False),
    sa.Column('source_proposal_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarters.id'], ),
    sa.ForeignKeyConstraint(['source_proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quarter_id', 'version_no', name='uq_schedule_version')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.Enum('MOTEUR', 'MANUEL', 'REPRISE', 'ECHANGE', name='assignmentorigin', native_enum=False, length=40), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('busy_operation', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['coverage_posts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_version_id', 'post_id', name='uq_assignment_post')
    )
    op.create_table('manual_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_version_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('from_profile_id', sa.Integer(), nullable=True),
    sa.Column('to_profile_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['coverage_posts.id'], ),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_versions.id'], ),
    sa.ForeignKeyConstraint(['to_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handover_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('requester_profile_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('admin_motive', sa.String(length=300), nullable=True),
    sa.Column('state', sa.Enum('BROUILLON', 'COLLECTE_VERTE', 'LISTE_FIGEE_VERTE', 'COLLECTE_ORANGE', 'LISTE_FIGEE_ORANGE', 'ATTRIBUEE', 'ESCALADE', 'ANNULEE', 'EXPIREE', name='handoverstate', native_enum=False, length=40), nullable=False),
    sa.Column('result_profile_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['requester_profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['result_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_a_id', sa.Integer(), nullable=False),
    sa.Column('assignment_b_id', sa.Integer(), nullable=False),
    sa.Column('proposer_profile_id', sa.Integer(), nullable=False),
    sa.Column('announced_profile_a_id', sa.Integer(), nullable=False),
    sa.Column('announced_profile_b_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PROPOSE', 'ACCEPTE_PAR_LES_DEUX', 'OFFICIEL', 'REFUSE', 'ANNULE', 'EXPIRE', name='swapstate', native_enum=False, length=40), nullable=False),
    sa.Column('accepted_a_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_b_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('refusal_reason', sa.Text(), nullable=True),
    sa.Column('equivalence_json', sa.Text(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announced_profile_a_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['announced_profile_b_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['assignment_a_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['assignment_b_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['proposer_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handover_waves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('VERTE', 'ORANGE', name='wavekind', native_enum=False, length=40), nullable=False),
    sa.Column('state', sa.Enum('OUVERTE', 'FIGEE', 'TIREE', 'SANS_CANDIDATURE', name='wavestate', native_enum=False, length=40), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('list_hash', sa.String(length=80), nullable=True),
    sa.Column('seed_commitment', sa.String(length=80), nullable=True),
    sa.Column('solicited_count', sa.Integer(), nullable=False),
    sa.Column('reminder_plan_json', sa.Text(), nullable=False),
    sa.Column('urgency_tier', sa.String(length=60), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['handover_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'kind', name='uq_wave_kind')
    )
    op.create_table('candidacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('DEPOSEE', 'VALIDE', 'EXCLUE', 'RETENUE', 'NON_RETENUE', name='candidacystate', native_enum=False, length=40), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['handover_waves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wave_id', 'profile_id', name='uq_candidacy')
    )
    op.create_table('wave_solicitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['professional_profiles.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['handover_waves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wave_id', 'profile_id', name='uq_solicitation')
    )
    op.create_table('draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('list_hash', sa.String(length=80), nullable=False),
    sa.Column('seed_commitment', sa.String(length=80), nullable=False),
    sa.Column('server_seed', sa.String(length=80), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('candidate_ids_json', sa.Text(), nullable=False),
    sa.Column('excluded_json', sa.Text(), nullable=False),
    sa.Column('winner_candidacy_id', sa.Integer(), nullable=True),
    sa.Column('winner_profile_id', sa.Integer(), nullable=True),
    sa.Column('proof_json', sa.Text(), nullable=False),
    sa.Column('single_candidate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wave_id'], ['handover_waves.id'], ),
    sa.ForeignKeyConstraint(['winner_candidacy_id'], ['candidacies.id'], ),
    sa.ForeignKeyConstraint(['winner_profile_id'], ['professional_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wave_id', name='uq_draw_wave')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draws')
    op.drop_table('wave_solicitations')
    op.drop_table('candidacies')
    op.drop_table('handover_waves')
    op.drop_table('swap_proposals')
    op.drop_table('handover_requests')
    op.drop_table('manual_corrections')
    op.drop_table('assignments')
    op.drop_table('schedule_versions')
    op.drop_table('proposal_assignments')
    op.drop_table('availabilities')
    op.drop_table('submissions')
    op.drop_table('quota_target_history')
    op.drop_table('proposals')
    op.drop_table('coverage_posts')
    op.drop_table('scenario_results')
    op.drop_table('quotite_history')
    op.drop_table('quota_targets')
    op.drop_table('quota_adjustments')
    op.drop_table('notifications')
    op.drop_table('garde_occurrences')
    op.drop_table('exemptions')
    op.drop_table('engine_runs')
    op.drop_table('eligibilities')
    op.drop_table('campaigns')
    op.drop_table('activity_periods')
    op.drop_table('scenarios')
    op.drop_table('quarters')
    op.drop_table('professional_profiles')
    op.drop_table('holiday_pair_members')
    op.drop_table('garde_types')
    op.drop_table('audit_events')
    op.drop_table('years')
    op.drop_table('users')
    op.drop_table('urgency_profiles')
    op.drop_table('rule_profiles')
    op.drop_table('rest_rules')
    op.drop_table('quota_categories')
    op.drop_table('holiday_pairs')
    op.drop_table('exchange_classes')
    # ### end Alembic commands ###
